[tbon]
interface_hint = "ib0"

[resource]
path = PATH
scheduling = SCHEDULING

[ingest.validator]
disable = true

[sched-fluxion-qmanager]
queue-policy= "fcfs_moldability"

[sched-fluxion-resource]
load-allowlist = "node,socket,core"
match-format = "rv1"
